/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.studentmanagementsystem;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import com.mycompany.studentmanagementsystem.StudentManagementSystem;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.JOptionPane;
/**
 *
 * @author dhaka
 */
public class Dashboard extends javax.swing.JFrame {

    
    /**
     * Creates new form Dashboard
     */
    public String enrollmentNumber;
    
    CardLayout cardLayout;    
    DefaultTableModel model=new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // Make all cells non-editable
    }    
};
    
    

    public Dashboard() {
        
        initComponents();
        cardLayout = (CardLayout) CardPanels.getLayout();
        DeleteStudentButton.setBackground(Color.white);
        UpdateStudentButton.setBackground(Color.white);
        RefreshStudentButton2.setBackground(Color.white);
        listTable.setModel(model);
//        StudentManagementSystem.getListFromDB();
        getTableLoaded();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddButton = new javax.swing.JButton();
        ListAllButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CardPanels = new javax.swing.JPanel();
        pnlCard1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        UpdateStudentButton = new javax.swing.JButton();
        DeleteStudentButton = new javax.swing.JButton();
        RefreshStudentButton2 = new javax.swing.JButton();
        pnlCard2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        YOAAddField = new javax.swing.JTextField();
        nameAddField = new javax.swing.JTextField();
        enrollmentAddField = new javax.swing.JTextField();
        classAddField = new javax.swing.JTextField();
        ageAddField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressAddField = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cancleButtonAddStudent = new javax.swing.JButton();
        saveButtonAddStudent1 = new javax.swing.JButton();
        pnlCard3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        YOAUpdate = new javax.swing.JTextField();
        NameUpdate = new javax.swing.JTextField();
        EnrollmentUpdate = new javax.swing.JTextField();
        classUpdate = new javax.swing.JTextField();
        ageUpdate = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressUpdate = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        cancleButtonAddStudent1 = new javax.swing.JButton();
        updateButtonAddStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1126, 551));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(202, 551));

        AddButton.setBackground(new java.awt.Color(102, 102, 102));
        AddButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add a student");
        AddButton.setBorder(null);
        AddButton.setFocusPainted(false);
        AddButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AddButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AddButtonFocusLost(evt);
            }
        });
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        ListAllButton.setBackground(new java.awt.Color(102, 102, 102));
        ListAllButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ListAllButton.setForeground(new java.awt.Color(255, 255, 255));
        ListAllButton.setText("List all students");
        ListAllButton.setBorder(null);
        ListAllButton.setFocusPainted(false);
        ListAllButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListAllButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListAllButtonFocusLost(evt);
            }
        });
        ListAllButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListAllButtonMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Log out");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ListAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton2)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(ListAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(605, 551));

        CardPanels.setLayout(new java.awt.CardLayout());

        pnlCard1.setBackground(new java.awt.Color(255, 255, 255));
        pnlCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Dashboard");

        jTextField6.setText("Search...");

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("search");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.setFocusPainted(false);

        listTable.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Enrollment number", "Name", "Class", "Age", "Year of admission", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTable.setFocusable(false);
        listTable.setRowHeight(45);
        listTable.setShowGrid(true);
        listTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listTable);

        UpdateStudentButton.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        UpdateStudentButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhaka\\Documents\\NetBeansProjects\\StudentManagementSystem\\src\\main\\java\\com\\mycompany\\studentmanagementsystem\\edit image.png")); // NOI18N
        UpdateStudentButton.setText("  Update student  ");
        UpdateStudentButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        UpdateStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateStudentButtonMouseClicked(evt);
            }
        });
        UpdateStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStudentButtonActionPerformed(evt);
            }
        });

        DeleteStudentButton.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        DeleteStudentButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhaka\\Documents\\NetBeansProjects\\StudentManagementSystem\\src\\main\\java\\com\\mycompany\\studentmanagementsystem\\delete image.png")); // NOI18N
        DeleteStudentButton.setText("  Delete student   ");
        DeleteStudentButton.setBorder(null);
        DeleteStudentButton.setMargin(new java.awt.Insets(2, 18, 3, 14));
        DeleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteStudentButtonActionPerformed(evt);
            }
        });

        RefreshStudentButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        RefreshStudentButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\dhaka\\Documents\\NetBeansProjects\\StudentManagementSystem\\src\\main\\java\\com\\mycompany\\studentmanagementsystem\\refreshicon-removebg-preview (1).png")); // NOI18N
        RefreshStudentButton2.setText("Refresh");
        RefreshStudentButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        RefreshStudentButton2.setBorderPainted(false);
        RefreshStudentButton2.setFocusPainted(false);
        RefreshStudentButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshStudentButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCard1Layout = new javax.swing.GroupLayout(pnlCard1);
        pnlCard1.setLayout(pnlCard1Layout);
        pnlCard1Layout.setHorizontalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addComponent(UpdateStudentButton)
                        .addGap(40, 40, 40)
                        .addComponent(DeleteStudentButton)
                        .addGap(40, 40, 40)
                        .addComponent(RefreshStudentButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        pnlCard1Layout.setVerticalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField6)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteStudentButton)
                        .addComponent(RefreshStudentButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(UpdateStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        CardPanels.add(pnlCard1, "card2");

        pnlCard2.setBackground(new java.awt.Color(255, 255, 255));
        pnlCard2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Year of admission :");
        pnlCard2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Name :");
        pnlCard2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setText("Enrollment no :");
        pnlCard2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setText("Class :");
        pnlCard2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setText("Address :");
        pnlCard2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setText("Age :");
        pnlCard2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 40, -1));

        YOAAddField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        YOAAddField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlCard2.add(YOAAddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 230, 30));

        nameAddField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        nameAddField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlCard2.add(nameAddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 230, 30));

        enrollmentAddField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        enrollmentAddField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlCard2.add(enrollmentAddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 230, 30));

        classAddField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        classAddField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        classAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classAddFieldActionPerformed(evt);
            }
        });
        pnlCard2.add(classAddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, 30));

        ageAddField.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ageAddField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlCard2.add(ageAddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 230, 30));

        addressAddField.setColumns(15);
        addressAddField.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        addressAddField.setRows(4);
        jScrollPane1.setViewportView(addressAddField);

        pnlCard2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 230, 100));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel3.setText("Add Student");
        pnlCard2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        cancleButtonAddStudent.setBackground(new java.awt.Color(0, 0, 0));
        cancleButtonAddStudent.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cancleButtonAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        cancleButtonAddStudent.setText("Cancle");
        cancleButtonAddStudent.setFocusPainted(false);
        cancleButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonAddStudentActionPerformed(evt);
            }
        });
        pnlCard2.add(cancleButtonAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, -1, -1));

        saveButtonAddStudent1.setBackground(new java.awt.Color(0, 153, 102));
        saveButtonAddStudent1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        saveButtonAddStudent1.setForeground(new java.awt.Color(255, 255, 255));
        saveButtonAddStudent1.setText("Save");
        saveButtonAddStudent1.setFocusPainted(false);
        saveButtonAddStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonAddStudent1ActionPerformed(evt);
            }
        });
        pnlCard2.add(saveButtonAddStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        CardPanels.add(pnlCard2, "card3");

        pnlCard3.setBackground(new java.awt.Color(255, 255, 255));
        pnlCard3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setText("Year of admission :");
        pnlCard3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setText("Name :");
        pnlCard3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setText("Enrollment no :");
        pnlCard3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setText("Class :");
        pnlCard3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel13.setText("Address :");
        pnlCard3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 90, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setText("Age :");
        pnlCard3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 40, -1));

        YOAUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        YOAUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlCard3.add(YOAUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 230, 30));

        NameUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        NameUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlCard3.add(NameUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 230, 30));

        EnrollmentUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        EnrollmentUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlCard3.add(EnrollmentUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 230, 30));

        classUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        classUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        classUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classUpdateActionPerformed(evt);
            }
        });
        pnlCard3.add(classUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 230, 30));

        ageUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ageUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlCard3.add(ageUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 230, 30));

        addressUpdate.setColumns(15);
        addressUpdate.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        addressUpdate.setRows(4);
        jScrollPane3.setViewportView(addressUpdate);

        pnlCard3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 230, 100));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel15.setText("Update a student");
        pnlCard3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        cancleButtonAddStudent1.setBackground(new java.awt.Color(0, 0, 0));
        cancleButtonAddStudent1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        cancleButtonAddStudent1.setForeground(new java.awt.Color(255, 255, 255));
        cancleButtonAddStudent1.setText("Cancle");
        cancleButtonAddStudent1.setFocusPainted(false);
        cancleButtonAddStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonAddStudent1ActionPerformed(evt);
            }
        });
        pnlCard3.add(cancleButtonAddStudent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, -1, -1));

        updateButtonAddStudent.setBackground(new java.awt.Color(0, 153, 102));
        updateButtonAddStudent.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        updateButtonAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        updateButtonAddStudent.setText("Update");
        updateButtonAddStudent.setFocusPainted(false);
        updateButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonAddStudentActionPerformed(evt);
            }
        });
        pnlCard3.add(updateButtonAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        CardPanels.add(pnlCard3, "card3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CardPanels, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CardPanels, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 0, 980, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ListAllButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListAllButtonMouseClicked
CardPanels.removeAll();
CardPanels.add(pnlCard1);
CardPanels.revalidate();
CardPanels.repaint();
    }//GEN-LAST:event_ListAllButtonMouseClicked
    
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

    }//GEN-LAST:event_AddButtonActionPerformed
    
    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        System.out.println("mouseButton is clicked");

        CardPanels.removeAll();
        CardPanels.add(pnlCard2);
        CardPanels.revalidate();
        CardPanels.repaint();
    }//GEN-LAST:event_AddButtonMouseClicked

    private void ListAllButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListAllButtonFocusGained
        ListAllButton.setBackground(Color.white);
        ListAllButton.setForeground(Color.black);    }//GEN-LAST:event_ListAllButtonFocusGained

    private void ListAllButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ListAllButtonFocusLost
        ListAllButton.setBackground(new Color(102, 102, 102));
        ListAllButton.setForeground(Color.white);
    }//GEN-LAST:event_ListAllButtonFocusLost

    private void AddButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddButtonFocusGained
        AddButton.setBackground(Color.white);
        AddButton.setForeground(Color.black);
    }//GEN-LAST:event_AddButtonFocusGained

    private void AddButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddButtonFocusLost
        AddButton.setBackground(new Color(102, 102, 102));
        AddButton.setForeground(Color.white);    }//GEN-LAST:event_AddButtonFocusLost

    private void classAddFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classAddFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classAddFieldActionPerformed

    private void saveButtonAddStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonAddStudent1ActionPerformed
       
    if(enrollmentAddField.getText().equals("")||nameAddField.getText().equals("")||classAddField.getText().equals("")||ageAddField.getText().equals("")||YOAAddField.getText().equals("")||addressAddField.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Please fill all the fields");
    }
    else{
        
     try{
        int enrollmentNo=Integer.parseInt(enrollmentAddField.getText());       
        String name = nameAddField.getText(); 
        String className = classAddField.getText(); 
        int age = Integer.parseInt(ageAddField.getText()); 
        int yearOfAdmission = Integer.parseInt(YOAAddField.getText());
        String address = addressAddField.getText(); 
    
    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_database", "root", "root");
    Statement sqlStatement = connection.createStatement();    
    
    String insertQuery = "INSERT INTO student_table (`enrollment no`, `name`, `class`, `age`, `year_of_admission`, `address`) VALUES ('"
                         + enrollmentNo + "', '" + name + "', '" + className + "', " + age + ", '" + yearOfAdmission + "', '" + address + "')";       
    
    int rowsAffected = sqlStatement.executeUpdate(insertQuery);
            sqlStatement.close();
            connection.close();
            
        CardPanels.removeAll();
        CardPanels.add(pnlCard1);
        CardPanels.revalidate();
        CardPanels.repaint(); 
        
        }  catch(SQLIntegrityConstraintViolationException SIe){
            JOptionPane.showMessageDialog(null, "Enrollment number already exists.");
        }catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }     
        model.setRowCount(0);
        model.setColumnCount(0);
        getTableLoaded();
             
    }
    }//GEN-LAST:event_saveButtonAddStudent1ActionPerformed

    private void classUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classUpdateActionPerformed

    private void updateButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonAddStudentActionPerformed
        
        if(EnrollmentUpdate.getText().equals("")||NameUpdate.getText().equals("")||classUpdate.getText().equals("")||ageUpdate.getText().equals("")||YOAUpdate.getText().equals("")||addressUpdate.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Please fill all the fields");
    }
    else{
        
        
        try{
        int enrollmentNo=Integer.parseInt(EnrollmentUpdate.getText());       
        String name = NameUpdate.getText(); 
        String className = classUpdate.getText(); 
        int age = Integer.parseInt(ageUpdate.getText()); 
        int yearOfAdmission = Integer.parseInt(YOAUpdate.getText());
        String address = addressUpdate.getText(); 
    
    Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_database", "root", "root");
    Statement sqlStatement = connection.createStatement();    
    
    String updateQuery = "UPDATE student_table SET `name` = '" + name + "', `class` = '" + className + "', `age` = " + age
                        + ", `year_of_admission` = '" + yearOfAdmission + "', `address` = '" + address + "' WHERE `enrollment no` = " + enrollmentNo;       
    
    int rowsAffected = sqlStatement.executeUpdate(updateQuery);
            sqlStatement.close();
            connection.close();
            
        CardPanels.removeAll();
        CardPanels.add(pnlCard1);
        CardPanels.revalidate();
        CardPanels.repaint(); 
        }  catch(SQLIntegrityConstraintViolationException SIe){
            JOptionPane.showMessageDialog(null, "Enrollment number already exists.");
        }catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }   
        
        model.setRowCount(0);
        model.setColumnCount(0);
        getTableLoaded();
         
        }
    }//GEN-LAST:event_updateButtonAddStudentActionPerformed

    private void UpdateStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateStudentButtonMouseClicked
        CardPanels.removeAll();
        CardPanels.add(pnlCard3);
        CardPanels.revalidate();
        CardPanels.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateStudentButtonMouseClicked

    private void UpdateStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStudentButtonActionPerformed
       
       try{ 
        String enrollmentNo=model.getValueAt(listTable.getSelectedRow(), 0).toString();
        String name=model.getValueAt(listTable.getSelectedRow(), 1).toString();
        String address=model.getValueAt(listTable.getSelectedRow(), 2).toString();
        String age=model.getValueAt(listTable.getSelectedRow(), 3).toString();
        String YOA=model.getValueAt(listTable.getSelectedRow(), 4).toString();
        String cls=model.getValueAt(listTable.getSelectedRow(), 5).toString();
        
        NameUpdate.setText(name);
        EnrollmentUpdate.setText(enrollmentNo);
        enrollmentNumber= enrollmentNo;
        classUpdate.setText(cls);
        ageUpdate.setText(age);
        YOAUpdate.setText(YOA);
        addressUpdate.setText(address);
        
           System.out.println(name);
           System.out.println(enrollmentNo);
           System.out.println(cls);
           System.out.println(age);
           System.out.println(YOA);
           System.out.println(address);
           
       }catch(ArrayIndexOutOfBoundsException Ae){
           System.out.println("Please select to update a student");
           JOptionPane.showMessageDialog(null, "Please select a student");
       }
                        
    }//GEN-LAST:event_UpdateStudentButtonActionPerformed

    private void listTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTableMouseClicked
       listTable.addMouseListener(new MouseAdapter(){
           @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) { // Double-click
                    listTable.editingCanceled(null);
                }
            }});
    }//GEN-LAST:event_listTableMouseClicked

    private void cancleButtonAddStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonAddStudent1ActionPerformed
        CardPanels.removeAll();
        CardPanels.add(pnlCard1);
        CardPanels.revalidate();
        CardPanels.repaint(); 
    }//GEN-LAST:event_cancleButtonAddStudent1ActionPerformed

    private void cancleButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonAddStudentActionPerformed
        CardPanels.removeAll();
        CardPanels.add(pnlCard1);
        CardPanels.revalidate();
        CardPanels.repaint();       
    }//GEN-LAST:event_cancleButtonAddStudentActionPerformed

    private void DeleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteStudentButtonActionPerformed
       
        try{
            String enrollmentNo=model.getValueAt(listTable.getSelectedRow(), 0).toString();       
            Connection connection= DriverManager.getConnection("jdbc:mysql://localhost:3306/student_database", "root", "root");
            Statement sqlStatement= connection.createStatement();
            int rowsAffected=sqlStatement.executeUpdate("DELETE FROM student_table WHERE `enrollment no` = "+enrollmentNo+";");
//            resultset.close();
            sqlStatement.close();
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(ArrayIndexOutOfBoundsException Ae){
            System.out.println("Please select a student");
            JOptionPane.showMessageDialog(null, "Please select a Student");
        }
        
        
        model.setRowCount(0);
        model.setColumnCount(0);
        getTableLoaded();

    }//GEN-LAST:event_DeleteStudentButtonActionPerformed

    private void RefreshStudentButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshStudentButton2ActionPerformed
        model.setRowCount(0);
        model.setColumnCount(0);
        getTableLoaded();
    }//GEN-LAST:event_RefreshStudentButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
     
    public void getTableLoaded(){
       try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_database", "root", "root")) {
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM student_table");

            // Get column names from metadata
            int columnCount = resultSet.getMetaData().getColumnCount();
            for (int i = 1; i <= columnCount; i++) {
                model.addColumn(resultSet.getMetaData().getColumnName(i));
            }

            // Populate table model with data
            while (resultSet.next()) {
                Object[] row = new Object[columnCount];
                for (int i = 1; i <= columnCount; i++) {
                    row[i - 1] = resultSet.getObject(i);
                }
                model.addRow(row);
            }

            resultSet.close();
            statement.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }  
}
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // Create a new table model
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
        
       
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JPanel CardPanels;
    private javax.swing.JButton DeleteStudentButton;
    private javax.swing.JTextField EnrollmentUpdate;
    private javax.swing.JButton ListAllButton;
    private javax.swing.JTextField NameUpdate;
    private javax.swing.JButton RefreshStudentButton2;
    private javax.swing.JButton UpdateStudentButton;
    private javax.swing.JTextField YOAAddField;
    private javax.swing.JTextField YOAUpdate;
    private javax.swing.JTextArea addressAddField;
    private javax.swing.JTextArea addressUpdate;
    private javax.swing.JTextField ageAddField;
    private javax.swing.JTextField ageUpdate;
    private javax.swing.JButton cancleButtonAddStudent;
    private javax.swing.JButton cancleButtonAddStudent1;
    private javax.swing.JTextField classAddField;
    private javax.swing.JTextField classUpdate;
    private javax.swing.JTextField enrollmentAddField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable listTable;
    private javax.swing.JTextField nameAddField;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JButton saveButtonAddStudent1;
    private javax.swing.JButton updateButtonAddStudent;
    // End of variables declaration//GEN-END:variables
}



